transform_type: 'lifting'
transform_name: "SimplicialCliqueLifting"
complex_dim: ${oc.select:dataset.parameters.max_dim_if_lifted,2}
preserve_edge_attr: ${oc.select:dataset.parameters.preserve_edge_attr_if_lifted,False}
signed: False
feature_lifting: ${oc.select:model.feature_encoder.feature_lifting,ProjectionSum}
neighborhoods: ${oc.select:model.backbone.neighborhoods,${oc.select:model.preprocessing_params.neighborhoods,null}}
